use_frameworks!

target 'HoradricExample' do
  pod 'Horadric', path: '../'
  pod 'WebPod', path: '../WebPod'
end

target 'HoradricExampleTests' do
  pod 'Horadric', path: '../'
  pod 'WebPod', path: '../WebPod'
end

